export const CURRENT_BLOCK = 'CURRENT/BLOCK';
export const BLOCKS_CHANHE = 'BLOCK/CHANGE';
export const BLOCKS_PHASE = 'BLOCK/BOUND';
export const SCREEN_STATE = 'BLOCK/STATE';
export const NEXT_BLOCK = 'NEXT/BLOCK';
export const SPEED_GRADE = 'SPEED/GRADE';
export const BUTTON_DISABLED = 'BUTTON/DISABLED';